name: Develop build

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install --file pom.xml "-Drevision=`echo ${{ github.ref_name }}|sed -e 's@/@-@'`-SNAPSHOT" -P jacocobadge
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        jacoco-csv-file: mockjdbc/target/site/jacoco/jacoco.csv
    - name: Push the badge
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Update coverage badge'
        add: .github/badges/jacoco.svg
